version: "3"
services:
  consul_server1:
    image: "consul:1.0.0"
    container_name: "consul_server1"
    hostname: "consul_server1"
    ports:
      - "8500:8500"
      - "8600:53"
    command: "agent -server -bootstrap -client=0.0.0.0 -ui"
  consul_server2:
    image: "consul:1.0.0"
    container_name: "consul_server2"
    hostname: "consul_server2"
    expose:
      - "8500"
      - "8600"
    command: "agent -server -join=consul_server1 -client=0.0.0.0"
    depends_on:
      - consul_server1
  akka_node1:
    image: "constructr-consul-demo:1.0"
    container_name: "akka_node1"
    hostname: "akka_node1"
    environment:
      - CONSUL_SERVER_ADDRESS=consul_server1
      - CONSUL_AGENT_NAME=akka_node1
    ports:
      - "8000:8000"
    depends_on:
      - consul_server1
      - consul_server2
    tty: true
  akka_node2:
    image: "constructr-consul-demo:1.0"
    container_name: "akka_node2"
    hostname: "akka_node2"
    environment:
      - CONSUL_SERVER_ADDRESS=consul_server1
      - CONSUL_AGENT_NAME=akka_node2
    depends_on:
      - consul_server1
      - consul_server2
    tty: true
